package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CartCartera generated by hbm2java
 */
public class CartCartera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcartera;
	private CartEstado cartEstado;
	private ContPlanCuenta contPlanCuenta;
	private ContTercero contTercero;
	private FactFactura factFactura;
	private Date fevencimiento;
	private BigDecimal nmsaldo;
	private Integer nmcuotas;
//	private Set cartPagos = new HashSet(0);

	public CartCartera() {
	}

	public CartCartera(int idcartera) {
		this.idcartera = idcartera;
	}

	public CartCartera(int idcartera, CartEstado cartEstado, ContPlanCuenta contPlanCuenta, ContTercero contTercero,
			FactFactura factFactura, Date fevencimiento, BigDecimal nmsaldo, Integer nmcuotas) {
		this.idcartera = idcartera;
		this.cartEstado = cartEstado;
		this.contPlanCuenta = contPlanCuenta;
		this.contTercero = contTercero;
		this.factFactura = factFactura;
		this.fevencimiento = fevencimiento;
		this.nmsaldo = nmsaldo;
		this.nmcuotas = nmcuotas;
	}

	public int getIdcartera() {
		return this.idcartera;
	}

	public void setIdcartera(int idcartera) {
		this.idcartera = idcartera;
	}

	public CartEstado getCartEstado() {
		return this.cartEstado;
	}

	public void setCartEstado(CartEstado cartEstado) {
		this.cartEstado = cartEstado;
	}

	public ContPlanCuenta getContPlanCuenta() {
		return this.contPlanCuenta;
	}

	public void setContPlanCuenta(ContPlanCuenta contPlanCuenta) {
		this.contPlanCuenta = contPlanCuenta;
	}

	public ContTercero getContTercero() {
		return this.contTercero;
	}

	public void setContTercero(ContTercero contTercero) {
		this.contTercero = contTercero;
	}

	public FactFactura getFactFactura() {
		return this.factFactura;
	}

	public void setFactFactura(FactFactura factFactura) {
		this.factFactura = factFactura;
	}

	public Date getFevencimiento() {
		return this.fevencimiento;
	}

	public void setFevencimiento(Date fevencimiento) {
		this.fevencimiento = fevencimiento;
	}

	public BigDecimal getNmsaldo() {
		return this.nmsaldo;
	}

	public void setNmsaldo(BigDecimal nmsaldo) {
		this.nmsaldo = nmsaldo;
	}

	public Integer getNmcuotas() {
		return this.nmcuotas;
	}

	public void setNmcuotas(Integer nmcuotas) {
		this.nmcuotas = nmcuotas;
	}

}
