package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * CartTipoPago generated by hbm2java
 */
public class CartTipoPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5870547884846326025L;
	private int idtipoPago;
	private String dsnombre;

	public CartTipoPago() {
	}

	public CartTipoPago(int idtipoPago) {
		this.idtipoPago = idtipoPago;
	}

	public CartTipoPago(int idtipoPago, String dsnombre) {
		this.idtipoPago = idtipoPago;
		this.dsnombre = dsnombre;
	}

	public int getIdtipoPago() {
		return this.idtipoPago;
	}

	public void setIdtipoPago(int idtipoPago) {
		this.idtipoPago = idtipoPago;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}
}
