package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CartPago generated by hbm2java
 */
public class CartPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpago;
	private CartCartera cartCartera;
	private CartFormaPago cartFormaPago;
	private CartTipoPago cartTipoPago;
	private ContMoneda contMoneda;
	private Date fepago;
	private BigDecimal nmvalor;
	private String dsdetalle;

	public CartPago() {
	}

	public CartPago(int idpago) {
		this.idpago = idpago;
	}

	public CartPago(int idpago, CartCartera cartCartera, CartFormaPago cartFormaPago, CartTipoPago cartTipoPago,
			ContMoneda contMoneda, Date fepago, BigDecimal nmvalor, String dsdetalle) {
		this.idpago = idpago;
		this.cartCartera = cartCartera;
		this.cartFormaPago = cartFormaPago;
		this.cartTipoPago = cartTipoPago;
		this.contMoneda = contMoneda;
		this.fepago = fepago;
		this.nmvalor = nmvalor;
		this.dsdetalle = dsdetalle;
	}

	public int getIdpago() {
		return this.idpago;
	}

	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	public CartCartera getCartCartera() {
		return this.cartCartera;
	}

	public void setCartCartera(CartCartera cartCartera) {
		this.cartCartera = cartCartera;
	}

	public CartFormaPago getCartFormaPago() {
		return this.cartFormaPago;
	}

	public void setCartFormaPago(CartFormaPago cartFormaPago) {
		this.cartFormaPago = cartFormaPago;
	}

	public CartTipoPago getCartTipoPago() {
		return this.cartTipoPago;
	}

	public void setCartTipoPago(CartTipoPago cartTipoPago) {
		this.cartTipoPago = cartTipoPago;
	}

	public ContMoneda getContMoneda() {
		return this.contMoneda;
	}

	public void setContMoneda(ContMoneda contMoneda) {
		this.contMoneda = contMoneda;
	}

	public Date getFepago() {
		return this.fepago;
	}

	public void setFepago(Date fepago) {
		this.fepago = fepago;
	}

	public BigDecimal getNmvalor() {
		return this.nmvalor;
	}

	public void setNmvalor(BigDecimal nmvalor) {
		this.nmvalor = nmvalor;
	}

	public String getDsdetalle() {
		return this.dsdetalle;
	}

	public void setDsdetalle(String dsdetalle) {
		this.dsdetalle = dsdetalle;
	}

}
