package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * CartFormaPago generated by hbm2java
 */
public class CartFormaPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idformaPago;
	private String dsnombre;

	public CartFormaPago() {
	}

	public CartFormaPago(int idformaPago) {
		this.idformaPago = idformaPago;
	}

	public CartFormaPago(int idformaPago, String dsnombre) {
		this.idformaPago = idformaPago;
		this.dsnombre = dsnombre;
	}

	public int getIdformaPago() {
		return this.idformaPago;
	}

	public void setIdformaPago(int idformaPago) {
		this.idformaPago = idformaPago;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}
}
