package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ContDetalleTransaccion generated by hbm2java
 */
public class ContDetalleTransaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iddetalle;
	private ContCentroCosto contCentroCosto;
	private ContNormaTipo contNormaTipo;
	private ContPlanCuenta contPlanCuenta;
	private ContTransaccionContable contTransaccionContable;
	private BigDecimal nmvalor;

	public ContDetalleTransaccion() {
	}

	
	public ContDetalleTransaccion(Integer iddetalle, ContNormaTipo contNormaTipo, ContPlanCuenta contPlanCuenta,
			ContTransaccionContable contTransaccionContable) {
		super();
		this.iddetalle = iddetalle;
		this.contNormaTipo = contNormaTipo;
		this.contPlanCuenta = contPlanCuenta;
		this.contTransaccionContable = contTransaccionContable;
	}



	public ContDetalleTransaccion(ContCentroCosto contCentroCosto, ContNormaTipo contNormaTipo,
			ContPlanCuenta contPlanCuenta, ContTransaccionContable contTransaccionContable) {
		super();
		this.contCentroCosto = contCentroCosto;
		this.contNormaTipo = contNormaTipo;
		this.contPlanCuenta = contPlanCuenta;
		this.contTransaccionContable = contTransaccionContable;
	}



	public ContDetalleTransaccion(ContCentroCosto contCentroCosto, ContNormaTipo contNormaTipo,
			ContPlanCuenta contPlanCuenta, ContTransaccionContable contTransaccionContable, BigDecimal nmvalor) {
		super();
		this.contCentroCosto = contCentroCosto;
		this.contNormaTipo = contNormaTipo;
		this.contPlanCuenta = contPlanCuenta;
		this.contTransaccionContable = contTransaccionContable;
		this.nmvalor = nmvalor;
	}

	public Integer getIddetalle() {
		return this.iddetalle;
	}

	public void setIddetalle(Integer iddetalle) {
		this.iddetalle = iddetalle;
	}

	public ContCentroCosto getContCentroCosto() {
		return this.contCentroCosto;
	}

	public void setContCentroCosto(ContCentroCosto contCentroCosto) {
		this.contCentroCosto = contCentroCosto;
	}

	public ContNormaTipo getContNormaTipo() {
		return this.contNormaTipo;
	}

	public void setContNormaTipo(ContNormaTipo contNormaTipo) {
		this.contNormaTipo = contNormaTipo;
	}

	public ContTransaccionContable getContTransaccionContable() {
		return this.contTransaccionContable;
	}

	public void setContTransaccionContable(ContTransaccionContable contTransaccionContable) {
		this.contTransaccionContable = contTransaccionContable;
	}

	public ContPlanCuenta getContPlanCuenta() {
		return contPlanCuenta;
	}


	public void setContPlanCuenta(ContPlanCuenta contPlanCuenta) {
		this.contPlanCuenta = contPlanCuenta;
	}


	public BigDecimal getNmvalor() {
		return this.nmvalor;
	}

	public void setNmvalor(BigDecimal nmvalor) {
		this.nmvalor = nmvalor;
	}

}
