package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ContMoneda generated by hbm2java
 */
public class ContMoneda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idmoneda;
	private String dscodigo;
	private String dsnombreMoneda;
	private String dssimbolo;
	private String dspaises;
//	private Set contTransaccionContables = new HashSet(0);
//	private Set cartPagos = new HashSet(0);
//	private Set contTerceros = new HashSet(0);

	public ContMoneda() {
	}

	public ContMoneda(int idmoneda, String dscodigo) {
		this.idmoneda = idmoneda;
		this.dscodigo = dscodigo;
	}

	public ContMoneda(int idmoneda, String dscodigo, String dsnombreMoneda, String dssimbolo, String dspaises) {
		this.idmoneda = idmoneda;
		this.dscodigo = dscodigo;
		this.dsnombreMoneda = dsnombreMoneda;
		this.dssimbolo = dssimbolo;
		this.dspaises = dspaises;
	}

	public int getIdmoneda() {
		return this.idmoneda;
	}

	public void setIdmoneda(int idmoneda) {
		this.idmoneda = idmoneda;
	}

	public String getDscodigo() {
		return this.dscodigo;
	}

	public void setDscodigo(String dscodigo) {
		this.dscodigo = dscodigo;
	}

	public String getDsnombreMoneda() {
		return this.dsnombreMoneda;
	}

	public void setDsnombreMoneda(String dsnombreMoneda) {
		this.dsnombreMoneda = dsnombreMoneda;
	}

	public String getDssimbolo() {
		return this.dssimbolo;
	}

	public void setDssimbolo(String dssimbolo) {
		this.dssimbolo = dssimbolo;
	}

	public String getDspaises() {
		return this.dspaises;
	}

	public void setDspaises(String dspaises) {
		this.dspaises = dspaises;
	}
}
