package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ContClasificacionIva generated by hbm2java
 */
public class ContClasificacionIva implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idclaseIva;
	private String dsnombre;
	private String dsdescripccion;
//	private Set contTerceros = new HashSet(0);

	public ContClasificacionIva() {
	}

	public ContClasificacionIva(int idclaseIva) {
		this.idclaseIva = idclaseIva;
	}

	public ContClasificacionIva(int idclaseIva, String dsnombre, String dsdescripccion) {
		this.idclaseIva = idclaseIva;
		this.dsnombre = dsnombre;
		this.dsdescripccion = dsdescripccion;
	}

	public int getIdclaseIva() {
		return this.idclaseIva;
	}

	public void setIdclaseIva(int idclaseIva) {
		this.idclaseIva = idclaseIva;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripccion() {
		return this.dsdescripccion;
	}

	public void setDsdescripccion(String dsdescripccion) {
		this.dsdescripccion = dsdescripccion;
	}
}
