package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ContOrganizacionInterna generated by hbm2java
 */
public class ContOrganizacionInterna implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idorganizacionInterna;
	private String dsnombreOrganizacion;
//	private Set factFacturas = new HashSet(0);
//	private Set rrhhRolesOrganizacioneses = new HashSet(0);
//	private Set contTransaccionContables = new HashSet(0);
//	private Set defiTransaccionAccions = new HashSet(0);

	public ContOrganizacionInterna() {
	}

	public ContOrganizacionInterna(int idorganizacionInterna) {
		this.idorganizacionInterna = idorganizacionInterna;
	}

	public ContOrganizacionInterna(int idorganizacionInterna, String dsnombreOrganizacion) {
		this.idorganizacionInterna = idorganizacionInterna;
		this.dsnombreOrganizacion = dsnombreOrganizacion;
	}

	public int getIdorganizacionInterna() {
		return this.idorganizacionInterna;
	}

	public void setIdorganizacionInterna(int idorganizacionInterna) {
		this.idorganizacionInterna = idorganizacionInterna;
	}

	public String getDsnombreOrganizacion() {
		return this.dsnombreOrganizacion;
	}

	public void setDsnombreOrganizacion(String dsnombreOrganizacion) {
		this.dsnombreOrganizacion = dsnombreOrganizacion;
	}
}
