package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ContCuentaGrupo generated by hbm2java
 */
public class ContCuentaGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcuentaGrupo;
	private ContNormaTipo contNormaTipo;
	private String dsdescripcion;
//	private Set contPlanCuentas = new HashSet(0);

	public ContCuentaGrupo() {
	}

	public ContCuentaGrupo(int idcuentaGrupo, ContNormaTipo contNormaTipo) {
		this.idcuentaGrupo = idcuentaGrupo;
		this.contNormaTipo = contNormaTipo;
	}

	public ContCuentaGrupo(int idcuentaGrupo, ContNormaTipo contNormaTipo, String dsdescripcion) {
		this.idcuentaGrupo = idcuentaGrupo;
		this.contNormaTipo = contNormaTipo;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdcuentaGrupo() {
		return this.idcuentaGrupo;
	}

	public void setIdcuentaGrupo(int idcuentaGrupo) {
		this.idcuentaGrupo = idcuentaGrupo;
	}

	public ContNormaTipo getContNormaTipo() {
		return this.contNormaTipo;
	}

	public void setContNormaTipo(ContNormaTipo contNormaTipo) {
		this.contNormaTipo = contNormaTipo;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}

}
