package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiCiudad generated by hbm2java
 */
public class DefiCiudad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idciudad;
	private DefiDepartamento defiDepartamento;
	private String dsnombre;
	private String dsdetalle;
//	private Set tercDireccions = new HashSet(0);
//	private Set defiTarifaIcas = new HashSet(0);

	public DefiCiudad() {
	}

	public DefiCiudad(String idciudad, DefiDepartamento defiDepartamento, String dsnombre) {
		this.idciudad = idciudad;
		this.defiDepartamento = defiDepartamento;
		this.dsnombre = dsnombre;
	}

	public DefiCiudad(String idciudad, DefiDepartamento defiDepartamento, String dsnombre, String dsdetalle) {
		this.idciudad = idciudad;
		this.defiDepartamento = defiDepartamento;
		this.dsnombre = dsnombre;
		this.dsdetalle = dsdetalle;
	}

	public String getIdciudad() {
		return this.idciudad;
	}

	public void setIdciudad(String idciudad) {
		this.idciudad = idciudad;
	}

	public DefiDepartamento getDefiDepartamento() {
		return this.defiDepartamento;
	}

	public void setDefiDepartamento(DefiDepartamento defiDepartamento) {
		this.defiDepartamento = defiDepartamento;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdetalle() {
		return this.dsdetalle;
	}

	public void setDsdetalle(String dsdetalle) {
		this.dsdetalle = dsdetalle;
	}
}
