package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiActividadIca generated by hbm2java
 */
public class DefiActividadIca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcodigoIca;
	private String dsactividadConcepto;
//	private Set defiTarifaIcas = new HashSet(0);
//	private Set contTerceros = new HashSet(0);

	public DefiActividadIca() {
	}

	public DefiActividadIca(int idcodigoIca) {
		this.idcodigoIca = idcodigoIca;
	}

	public DefiActividadIca(int idcodigoIca, String dsactividadConcepto) {
		this.idcodigoIca = idcodigoIca;
		this.dsactividadConcepto = dsactividadConcepto;
	}

	public int getIdcodigoIca() {
		return this.idcodigoIca;
	}

	public void setIdcodigoIca(int idcodigoIca) {
		this.idcodigoIca = idcodigoIca;
	}

	public String getDsactividadConcepto() {
		return this.dsactividadConcepto;
	}

	public void setDsactividadConcepto(String dsactividadConcepto) {
		this.dsactividadConcepto = dsactividadConcepto;
	}

}
