package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiConceptoRf generated by hbm2java
 */
public class DefiConceptoRf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idconceptorf;
	private String dsconcepto;
	private String dsdescripcion;
//	private Set defiTarifaRfs = new HashSet(0);
//	private Set contTerceros = new HashSet(0);

	public DefiConceptoRf() {
	}

	public DefiConceptoRf(int idconceptorf) {
		this.idconceptorf = idconceptorf;
	}

	public DefiConceptoRf(int idconceptorf, String dsconcepto, String dsdescripcion) {
		this.idconceptorf = idconceptorf;
		this.dsconcepto = dsconcepto;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdconceptorf() {
		return this.idconceptorf;
	}

	public void setIdconceptorf(int idconceptorf) {
		this.idconceptorf = idconceptorf;
	}

	public String getDsconcepto() {
		return this.dsconcepto;
	}

	public void setDsconcepto(String dsconcepto) {
		this.dsconcepto = dsconcepto;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
