package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiDepartamento generated by hbm2java
 */
public class DefiDepartamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String iddepartamento;
	private DefiPais defiPais;
	private String dsnombre;
	private String dsdetalle;
//	private Set tercDireccions = new HashSet(0);
//	private Set defiCiudads = new HashSet(0);

	public DefiDepartamento() {
	}

	public DefiDepartamento(String iddepartamento, DefiPais defiPais) {
		this.iddepartamento = iddepartamento;
		this.defiPais = defiPais;
	}

	public DefiDepartamento(String iddepartamento, DefiPais defiPais, String dsnombre, String dsdetalle) {
		this.iddepartamento = iddepartamento;
		this.defiPais = defiPais;
		this.dsnombre = dsnombre;
		this.dsdetalle = dsdetalle;
	}

	public String getIddepartamento() {
		return this.iddepartamento;
	}

	public void setIddepartamento(String iddepartamento) {
		this.iddepartamento = iddepartamento;
	}

	public DefiPais getDefiPais() {
		return this.defiPais;
	}

	public void setDefiPais(DefiPais defiPais) {
		this.defiPais = defiPais;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdetalle() {
		return this.dsdetalle;
	}

	public void setDsdetalle(String dsdetalle) {
		this.dsdetalle = dsdetalle;
	}
}
