package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiTipoDato generated by hbm2java
 */
public class DefiTipoDato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtipoDato;
	private String dsnombre;
	private String dsdescripcion;
//	private Set defiParametros = new HashSet(0);
//	private Set defiAccions = new HashSet(0);

	public DefiTipoDato() {
	}

	public DefiTipoDato(int idtipoDato) {
		this.idtipoDato = idtipoDato;
	}

	public DefiTipoDato(int idtipoDato, String dsnombre, String dsdescripcion) {
		this.idtipoDato = idtipoDato;
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdtipoDato() {
		return this.idtipoDato;
	}

	public void setIdtipoDato(int idtipoDato) {
		this.idtipoDato = idtipoDato;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
