package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiAccion generated by hbm2java
 */
public class DefiAccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1313989466968679130L;
	private int idaccion;
	private DefiAccionTipo defiAccionTipo;
	private DefiTipoDato defiTipoDato;
	private String dsnombre;
	private String dsetiqueta;
//	private Set defiParametros = new HashSet(0);
//	private Set defiAccionReglas = new HashSet(0);

	public DefiAccion() {
	}

	public DefiAccion(int idaccion, DefiAccionTipo defiAccionTipo, DefiTipoDato defiTipoDato) {
		this.idaccion = idaccion;
		this.defiAccionTipo = defiAccionTipo;
		this.defiTipoDato = defiTipoDato;
	}

	public DefiAccion(int idaccion, DefiAccionTipo defiAccionTipo, DefiTipoDato defiTipoDato, String dsnombre, String dsetiqueta) {
		this.idaccion = idaccion;
		this.defiAccionTipo = defiAccionTipo;
		this.defiTipoDato = defiTipoDato;
		this.dsnombre = dsnombre;
		this.dsetiqueta = dsetiqueta;
	}

	public int getIdaccion() {
		return this.idaccion;
	}

	public void setIdaccion(int idaccion) {
		this.idaccion = idaccion;
	}

	public DefiAccionTipo getDefiAccionTipo() {
		return this.defiAccionTipo;
	}

	public void setDefiAccionTipo(DefiAccionTipo defiAccionTipo) {
		this.defiAccionTipo = defiAccionTipo;
	}

	public DefiTipoDato getDefiTipoDato() {
		return this.defiTipoDato;
	}

	public void setDefiTipoDato(DefiTipoDato defiTipoDato) {
		this.defiTipoDato = defiTipoDato;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsetiqueta() {
		return this.dsetiqueta;
	}

	public void setDsetiqueta(String dsetiqueta) {
		this.dsetiqueta = dsetiqueta;
	}
}
