package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiPais generated by hbm2java
 */
public class DefiPais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idpais;
	private String dsnombre;
	private String dsdetalle;
//	private Set defiDepartamentos = new HashSet(0);
//	private Set tercDireccions = new HashSet(0);

	public DefiPais() {
	}

	public DefiPais(String idpais) {
		this.idpais = idpais;
	}

	public DefiPais(String idpais, String dsnombre, String dsdetalle) {
		this.idpais = idpais;
		this.dsnombre = dsnombre;
		this.dsdetalle = dsdetalle;
	}

	public String getIdpais() {
		return this.idpais;
	}

	public void setIdpais(String idpais) {
		this.idpais = idpais;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdetalle() {
		return this.dsdetalle;
	}

	public void setDsdetalle(String dsdetalle) {
		this.dsdetalle = dsdetalle;
	}
}
