package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiTipoContribuyente generated by hbm2java
 */
public class DefiTipoContribuyente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtipoContribuyente;
	private String dsnombre;
	private String dsdescripcion;

	public DefiTipoContribuyente() {
	}

	public DefiTipoContribuyente(int idtipoContribuyente) {
		this.idtipoContribuyente = idtipoContribuyente;
	}

	public DefiTipoContribuyente(int idtipoContribuyente, String dsnombre, String dsdescripcion) {
		this.idtipoContribuyente = idtipoContribuyente;
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdtipoContribuyente() {
		return this.idtipoContribuyente;
	}

	public void setIdtipoContribuyente(int idtipoContribuyente) {
		this.idtipoContribuyente = idtipoContribuyente;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}

}
