package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiAccionRegla generated by hbm2java
 */
public class DefiAccionRegla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idaccionRegla;
	private DefiAccion defiAccion;
	private DefiTransaccionAccion defiTransaccionAccion;
	private Integer nmprioridad;
	private String dsconcidicional;
	private Integer nmcondicional;

	public DefiAccionRegla() {
	}

	public DefiAccionRegla(int idaccionRegla) {
		this.idaccionRegla = idaccionRegla;
	}

	public DefiAccionRegla(int idaccionRegla, DefiAccion defiAccion, DefiTransaccionAccion defiTransaccionAccion,
			Integer nmprioridad, String dsconcidicional, Integer nmcondicional) {
		this.idaccionRegla = idaccionRegla;
		this.defiAccion = defiAccion;
		this.defiTransaccionAccion = defiTransaccionAccion;
		this.nmprioridad = nmprioridad;
		this.dsconcidicional = dsconcidicional;
		this.nmcondicional = nmcondicional;
	}

	public int getIdaccionRegla() {
		return this.idaccionRegla;
	}

	public void setIdaccionRegla(int idaccionRegla) {
		this.idaccionRegla = idaccionRegla;
	}

	public DefiAccion getDefiAccion() {
		return this.defiAccion;
	}

	public void setDefiAccion(DefiAccion defiAccion) {
		this.defiAccion = defiAccion;
	}

	public DefiTransaccionAccion getDefiTransaccionAccion() {
		return this.defiTransaccionAccion;
	}

	public void setDefiTransaccionAccion(DefiTransaccionAccion defiTransaccionAccion) {
		this.defiTransaccionAccion = defiTransaccionAccion;
	}

	public Integer getNmprioridad() {
		return this.nmprioridad;
	}

	public void setNmprioridad(Integer nmprioridad) {
		this.nmprioridad = nmprioridad;
	}

	public String getDsconcidicional() {
		return this.dsconcidicional;
	}

	public void setDsconcidicional(String dsconcidicional) {
		this.dsconcidicional = dsconcidicional;
	}

	public Integer getNmcondicional() {
		return this.nmcondicional;
	}

	public void setNmcondicional(Integer nmcondicional) {
		this.nmcondicional = nmcondicional;
	}

}
