package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiTransaccionAccion generated by hbm2java
 */
public class DefiTransaccionAccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3474399076693657373L;
	private int idtransaccionAccion;
	private ContNormaTipo contNormaTipo;
	private ContOrganizacionInterna contOrganizacionInterna;
	private ContPlanCuenta contPlanCuenta;
	private ContTransaccionTipo contTransaccionTipo;
//	private Set defiAccionReglas = new HashSet(0);
//	private Set tercTerceroCuentas = new HashSet(0);

	public DefiTransaccionAccion() {
	}

	public DefiTransaccionAccion(int idtransaccionAccion, ContPlanCuenta contPlanCuenta, ContTransaccionTipo contTransaccionTipo) {
		this.idtransaccionAccion = idtransaccionAccion;
		this.contPlanCuenta = contPlanCuenta;
		this.contTransaccionTipo = contTransaccionTipo;
	}

	public DefiTransaccionAccion(int idtransaccionAccion, ContNormaTipo contNormaTipo,
			ContOrganizacionInterna contOrganizacionInterna, ContPlanCuenta contPlanCuenta,
			ContTransaccionTipo contTransaccionTipo) {
		this.idtransaccionAccion = idtransaccionAccion;
		this.contNormaTipo = contNormaTipo;
		this.contOrganizacionInterna = contOrganizacionInterna;
		this.contPlanCuenta = contPlanCuenta;
		this.contTransaccionTipo = contTransaccionTipo;
	}

	public int getIdtransaccionAccion() {
		return this.idtransaccionAccion;
	}

	public void setIdtransaccionAccion(int idtransaccionAccion) {
		this.idtransaccionAccion = idtransaccionAccion;
	}

	public ContNormaTipo getContNormaTipo() {
		return this.contNormaTipo;
	}

	public void setContNormaTipo(ContNormaTipo contNormaTipo) {
		this.contNormaTipo = contNormaTipo;
	}

	public ContOrganizacionInterna getContOrganizacionInterna() {
		return this.contOrganizacionInterna;
	}

	public void setContOrganizacionInterna(ContOrganizacionInterna contOrganizacionInterna) {
		this.contOrganizacionInterna = contOrganizacionInterna;
	}

	public ContPlanCuenta getContPlanCuenta() {
		return this.contPlanCuenta;
	}

	public void setContPlanCuenta(ContPlanCuenta contPlanCuenta) {
		this.contPlanCuenta = contPlanCuenta;
	}

	public ContTransaccionTipo getContTransaccionTipo() {
		return this.contTransaccionTipo;
	}

	public void setContTransaccionTipo(ContTransaccionTipo contTransaccionTipo) {
		this.contTransaccionTipo = contTransaccionTipo;
	}

}
