package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * DefiTarifaRf generated by hbm2java
 */
public class DefiTarifaRf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtarifarf;
	private DefiConceptoRf defiConceptoRf;
	private Integer nmperiodo;
	private String snaplicaUvt;
	private Integer nmbaseUvtInf;
	private Integer nmbaseUvtSup;
	private BigDecimal nmbaseInferior;
	private BigDecimal nmbaseSuperior;
	private Double nmtarifa;

	public DefiTarifaRf() {
	}

	public DefiTarifaRf(int idtarifarf, DefiConceptoRf defiConceptoRf) {
		this.idtarifarf = idtarifarf;
		this.defiConceptoRf = defiConceptoRf;
	}

	public DefiTarifaRf(int idtarifarf, DefiConceptoRf defiConceptoRf, Integer nmperiodo, String snaplicaUvt,
			Integer nmbaseUvtInf, Integer nmbaseUvtSup, BigDecimal nmbaseInferior, BigDecimal nmbaseSuperior,
			Double nmtarifa) {
		this.idtarifarf = idtarifarf;
		this.defiConceptoRf = defiConceptoRf;
		this.nmperiodo = nmperiodo;
		this.snaplicaUvt = snaplicaUvt;
		this.nmbaseUvtInf = nmbaseUvtInf;
		this.nmbaseUvtSup = nmbaseUvtSup;
		this.nmbaseInferior = nmbaseInferior;
		this.nmbaseSuperior = nmbaseSuperior;
		this.nmtarifa = nmtarifa;
	}

	public int getIdtarifarf() {
		return this.idtarifarf;
	}

	public void setIdtarifarf(int idtarifarf) {
		this.idtarifarf = idtarifarf;
	}

	public DefiConceptoRf getDefiConceptoRf() {
		return this.defiConceptoRf;
	}

	public void setDefiConceptoRf(DefiConceptoRf defiConceptoRf) {
		this.defiConceptoRf = defiConceptoRf;
	}

	public Integer getNmperiodo() {
		return this.nmperiodo;
	}

	public void setNmperiodo(Integer nmperiodo) {
		this.nmperiodo = nmperiodo;
	}

	public String getSnaplicaUvt() {
		return this.snaplicaUvt;
	}

	public void setSnaplicaUvt(String snaplicaUvt) {
		this.snaplicaUvt = snaplicaUvt;
	}

	public Integer getNmbaseUvtInf() {
		return this.nmbaseUvtInf;
	}

	public void setNmbaseUvtInf(Integer nmbaseUvtInf) {
		this.nmbaseUvtInf = nmbaseUvtInf;
	}

	public Integer getNmbaseUvtSup() {
		return this.nmbaseUvtSup;
	}

	public void setNmbaseUvtSup(Integer nmbaseUvtSup) {
		this.nmbaseUvtSup = nmbaseUvtSup;
	}

	public BigDecimal getNmbaseInferior() {
		return this.nmbaseInferior;
	}

	public void setNmbaseInferior(BigDecimal nmbaseInferior) {
		this.nmbaseInferior = nmbaseInferior;
	}

	public BigDecimal getNmbaseSuperior() {
		return this.nmbaseSuperior;
	}

	public void setNmbaseSuperior(BigDecimal nmbaseSuperior) {
		this.nmbaseSuperior = nmbaseSuperior;
	}

	public Double getNmtarifa() {
		return this.nmtarifa;
	}

	public void setNmtarifa(Double nmtarifa) {
		this.nmtarifa = nmtarifa;
	}

}
