package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * DefiTarifaIca generated by hbm2java
 */
public class DefiTarifaIca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtarifa;
	private DefiActividadIca defiActividadIca;
	private DefiCiudad defiCiudad;
	private Integer nmperiodo;
	private Double nmbaseUvt;
	private BigDecimal nmbaseMinima;
	private Double nmtarifa;

	public DefiTarifaIca() {
	}

	public DefiTarifaIca(int idtarifa, DefiCiudad defiCiudad) {
		this.idtarifa = idtarifa;
		this.defiCiudad = defiCiudad;
	}

	public DefiTarifaIca(int idtarifa, DefiActividadIca defiActividadIca, DefiCiudad defiCiudad, Integer nmperiodo,
			Double nmbaseUvt, BigDecimal nmbaseMinima, Double nmtarifa) {
		this.idtarifa = idtarifa;
		this.defiActividadIca = defiActividadIca;
		this.defiCiudad = defiCiudad;
		this.nmperiodo = nmperiodo;
		this.nmbaseUvt = nmbaseUvt;
		this.nmbaseMinima = nmbaseMinima;
		this.nmtarifa = nmtarifa;
	}

	public int getIdtarifa() {
		return this.idtarifa;
	}

	public void setIdtarifa(int idtarifa) {
		this.idtarifa = idtarifa;
	}

	public DefiActividadIca getDefiActividadIca() {
		return this.defiActividadIca;
	}

	public void setDefiActividadIca(DefiActividadIca defiActividadIca) {
		this.defiActividadIca = defiActividadIca;
	}

	public DefiCiudad getDefiCiudad() {
		return this.defiCiudad;
	}

	public void setDefiCiudad(DefiCiudad defiCiudad) {
		this.defiCiudad = defiCiudad;
	}

	public Integer getNmperiodo() {
		return this.nmperiodo;
	}

	public void setNmperiodo(Integer nmperiodo) {
		this.nmperiodo = nmperiodo;
	}

	public Double getNmbaseUvt() {
		return this.nmbaseUvt;
	}

	public void setNmbaseUvt(Double nmbaseUvt) {
		this.nmbaseUvt = nmbaseUvt;
	}

	public BigDecimal getNmbaseMinima() {
		return this.nmbaseMinima;
	}

	public void setNmbaseMinima(BigDecimal nmbaseMinima) {
		this.nmbaseMinima = nmbaseMinima;
	}

	public Double getNmtarifa() {
		return this.nmtarifa;
	}

	public void setNmtarifa(Double nmtarifa) {
		this.nmtarifa = nmtarifa;
	}

}
