package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiSede generated by hbm2java
 */
public class DefiSede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idsede;
	private Long idorganizacionInterna;
	private String dsnombre;
	private String dsdireccion;
	private String dstelefono;
//	private Set prodProductoSedes = new HashSet(0);

	public DefiSede() {
	}

	public DefiSede(int idsede) {
		this.idsede = idsede;
	}

	public DefiSede(int idsede, Long idorganizacionInterna, String dsnombre, String dsdireccion, String dstelefono) {
		this.idsede = idsede;
		this.idorganizacionInterna = idorganizacionInterna;
		this.dsnombre = dsnombre;
		this.dsdireccion = dsdireccion;
		this.dstelefono = dstelefono;
	}

	public int getIdsede() {
		return this.idsede;
	}

	public void setIdsede(int idsede) {
		this.idsede = idsede;
	}

	public Long getIdorganizacionInterna() {
		return this.idorganizacionInterna;
	}

	public void setIdorganizacionInterna(Long idorganizacionInterna) {
		this.idorganizacionInterna = idorganizacionInterna;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdireccion() {
		return this.dsdireccion;
	}

	public void setDsdireccion(String dsdireccion) {
		this.dsdireccion = dsdireccion;
	}

	public String getDstelefono() {
		return this.dstelefono;
	}

	public void setDstelefono(String dstelefono) {
		this.dstelefono = dstelefono;
	}
}
