package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * DefiAccionTipo generated by hbm2java
 */
public class DefiAccionTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idaccionTipo;
	private String dsnombre;
	private String dsetiqueta;
//	private Set defiAccions = new HashSet(0);

	public DefiAccionTipo() {
	}

	public DefiAccionTipo(int idaccionTipo, String dsnombre) {
		this.idaccionTipo = idaccionTipo;
		this.dsnombre = dsnombre;
	}

	public DefiAccionTipo(int idaccionTipo, String dsnombre, String dsetiqueta) {
		this.idaccionTipo = idaccionTipo;
		this.dsnombre = dsnombre;
		this.dsetiqueta = dsetiqueta;
	}

	public int getIdaccionTipo() {
		return this.idaccionTipo;
	}

	public void setIdaccionTipo(int idaccionTipo) {
		this.idaccionTipo = idaccionTipo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsetiqueta() {
		return this.dsetiqueta;
	}

	public void setDsetiqueta(String dsetiqueta) {
		this.dsetiqueta = dsetiqueta;
	}
}
