package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * FactDetalleFacturaTipo generated by hbm2java
 */
public class FactDetalleFacturaTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iddetalleFacturaTipo;
	private String dsnombre;
	private String dsdescripcion;

	public FactDetalleFacturaTipo() {
	}

	public FactDetalleFacturaTipo(String dsnombre, String dsdescripcion) {
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public Integer getIddetalleFacturaTipo() {
		return this.iddetalleFacturaTipo;
	}

	public void setIddetalleFacturaTipo(Integer iddetalleFacturaTipo) {
		this.iddetalleFacturaTipo = iddetalleFacturaTipo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
