package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdProductoCategoria generated by hbm2java
 */
public class ProdProductoCategoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idproductoCategoria;
	private ProdCategoria prodCategoria;
	private ProdProducto prodProducto;

	public ProdProductoCategoria() {
	}

	public ProdProductoCategoria(int idproductoCategoria) {
		this.idproductoCategoria = idproductoCategoria;
	}

	public ProdProductoCategoria(int idproductoCategoria, ProdCategoria prodCategoria, ProdProducto prodProducto) {
		this.idproductoCategoria = idproductoCategoria;
		this.prodCategoria = prodCategoria;
		this.prodProducto = prodProducto;
	}

	public int getIdproductoCategoria() {
		return this.idproductoCategoria;
	}

	public void setIdproductoCategoria(int idproductoCategoria) {
		this.idproductoCategoria = idproductoCategoria;
	}

	public ProdCategoria getProdCategoria() {
		return this.prodCategoria;
	}

	public void setProdCategoria(ProdCategoria prodCategoria) {
		this.prodCategoria = prodCategoria;
	}

	public ProdProducto getProdProducto() {
		return this.prodProducto;
	}

	public void setProdProducto(ProdProducto prodProducto) {
		this.prodProducto = prodProducto;
	}

}
