package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdProductoSede generated by hbm2java
 */
public class ProdProductoSede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idprodSede;
	private DefiSede defiSede;
	private ProdProducto prodProducto;
	private Integer idtransaccionAccion;
	private Integer nmprecioVenta;
	private Integer nmprecioCompra;
	private Integer nmsaldo;
	private Integer nmimpuesto;
	private Integer nmcantidadMin;
	private Integer nmcantidadMax;

	public ProdProductoSede() {
	}

	public ProdProductoSede(int idprodSede) {
		this.idprodSede = idprodSede;
	}

	public ProdProductoSede(int idprodSede, DefiSede defiSede, ProdProducto prodProducto, Integer idtransaccionAccion,
			Integer nmprecioVenta, Integer nmprecioCompra, Integer nmsaldo, Integer nmimpuesto, Integer nmcantidadMin,
			Integer nmcantidadMax) {
		this.idprodSede = idprodSede;
		this.defiSede = defiSede;
		this.prodProducto = prodProducto;
		this.idtransaccionAccion = idtransaccionAccion;
		this.nmprecioVenta = nmprecioVenta;
		this.nmprecioCompra = nmprecioCompra;
		this.nmsaldo = nmsaldo;
		this.nmimpuesto = nmimpuesto;
		this.nmcantidadMin = nmcantidadMin;
		this.nmcantidadMax = nmcantidadMax;
	}

	public int getIdprodSede() {
		return this.idprodSede;
	}

	public void setIdprodSede(int idprodSede) {
		this.idprodSede = idprodSede;
	}

	public DefiSede getDefiSede() {
		return this.defiSede;
	}

	public void setDefiSede(DefiSede defiSede) {
		this.defiSede = defiSede;
	}

	public ProdProducto getProdProducto() {
		return this.prodProducto;
	}

	public void setProdProducto(ProdProducto prodProducto) {
		this.prodProducto = prodProducto;
	}

	public Integer getIdtransaccionAccion() {
		return this.idtransaccionAccion;
	}

	public void setIdtransaccionAccion(Integer idtransaccionAccion) {
		this.idtransaccionAccion = idtransaccionAccion;
	}

	public Integer getNmprecioVenta() {
		return this.nmprecioVenta;
	}

	public void setNmprecioVenta(Integer nmprecioVenta) {
		this.nmprecioVenta = nmprecioVenta;
	}

	public Integer getNmprecioCompra() {
		return this.nmprecioCompra;
	}

	public void setNmprecioCompra(Integer nmprecioCompra) {
		this.nmprecioCompra = nmprecioCompra;
	}

	public Integer getNmsaldo() {
		return this.nmsaldo;
	}

	public void setNmsaldo(Integer nmsaldo) {
		this.nmsaldo = nmsaldo;
	}

	public Integer getNmimpuesto() {
		return this.nmimpuesto;
	}

	public void setNmimpuesto(Integer nmimpuesto) {
		this.nmimpuesto = nmimpuesto;
	}

	public Integer getNmcantidadMin() {
		return this.nmcantidadMin;
	}

	public void setNmcantidadMin(Integer nmcantidadMin) {
		this.nmcantidadMin = nmcantidadMin;
	}

	public Integer getNmcantidadMax() {
		return this.nmcantidadMax;
	}

	public void setNmcantidadMax(Integer nmcantidadMax) {
		this.nmcantidadMax = nmcantidadMax;
	}

}
