package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdColor generated by hbm2java
 */
public class ProdColor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcolor;
	private String dsdescripccion;
//	private Set prodProductos = new HashSet(0);

	public ProdColor() {
	}

	public ProdColor(int idcolor) {
		this.idcolor = idcolor;
	}

	public ProdColor(int idcolor, String dsdescripccion) {
		this.idcolor = idcolor;
	}

	public int getIdcolor() {
		return this.idcolor;
	}

	public void setIdcolor(int idcolor) {
		this.idcolor = idcolor;
	}

	public String getDsdescripccion() {
		return this.dsdescripccion;
	}

	public void setDsdescripccion(String dsdescripccion) {
		this.dsdescripccion = dsdescripccion;
	}
}
