package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdProducto generated by hbm2java
 */
public class ProdProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idproducto;
	private ProdColor prodColor;
	private ProdProductoTipo prodProductoTipo;
	private ProdTalla prodTalla;
	private String dscodigo;
	private Long nmcodigoEan13;
	private String dsnombre;
	private String dsnombreCorto;
	private String dsdescripcion;
	private Integer nmprecioVenta;
	private Integer nmprecioCompra;
	private Integer nmsaldo;
	private String dsimagenProducto;
	private String dsimagenFichatec;
	private Integer nmimpuesto;
	private Integer mncantidadMin;
	private String mncantidadMax;
//	private Set prodProductoCategorias = new HashSet(0);
//	private Set prodProductoSedes = new HashSet(0);
//	private Set factDetalleFacturas = new HashSet(0);

	public ProdProducto() {
	}

	public ProdProducto(String idproducto) {
		this.idproducto = idproducto;
	}

	public ProdProducto(String idproducto, ProdColor prodColor, ProdProductoTipo prodProductoTipo, ProdTalla prodTalla,
			String dscodigo, Long nmcodigoEan13, String dsnombre, String dsnombreCorto, String dsdescripcion,
			Integer nmprecioVenta, Integer nmprecioCompra, Integer nmsaldo, String dsimagenProducto,
			String dsimagenFichatec, Integer nmimpuesto, Integer mncantidadMin, String mncantidadMax) {
		this.idproducto = idproducto;
		this.prodColor = prodColor;
		this.prodProductoTipo = prodProductoTipo;
		this.prodTalla = prodTalla;
		this.dscodigo = dscodigo;
		this.nmcodigoEan13 = nmcodigoEan13;
		this.dsnombre = dsnombre;
		this.dsnombreCorto = dsnombreCorto;
		this.dsdescripcion = dsdescripcion;
		this.nmprecioVenta = nmprecioVenta;
		this.nmprecioCompra = nmprecioCompra;
		this.nmsaldo = nmsaldo;
		this.dsimagenProducto = dsimagenProducto;
		this.dsimagenFichatec = dsimagenFichatec;
		this.nmimpuesto = nmimpuesto;
		this.mncantidadMin = mncantidadMin;
		this.mncantidadMax = mncantidadMax;
	}

	public String getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(String idproducto) {
		this.idproducto = idproducto;
	}

	public ProdColor getProdColor() {
		return this.prodColor;
	}

	public void setProdColor(ProdColor prodColor) {
		this.prodColor = prodColor;
	}

	public ProdProductoTipo getProdProductoTipo() {
		return this.prodProductoTipo;
	}

	public void setProdProductoTipo(ProdProductoTipo prodProductoTipo) {
		this.prodProductoTipo = prodProductoTipo;
	}

	public ProdTalla getProdTalla() {
		return this.prodTalla;
	}

	public void setProdTalla(ProdTalla prodTalla) {
		this.prodTalla = prodTalla;
	}

	public String getDscodigo() {
		return this.dscodigo;
	}

	public void setDscodigo(String dscodigo) {
		this.dscodigo = dscodigo;
	}

	public Long getNmcodigoEan13() {
		return this.nmcodigoEan13;
	}

	public void setNmcodigoEan13(Long nmcodigoEan13) {
		this.nmcodigoEan13 = nmcodigoEan13;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsnombreCorto() {
		return this.dsnombreCorto;
	}

	public void setDsnombreCorto(String dsnombreCorto) {
		this.dsnombreCorto = dsnombreCorto;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}

	public Integer getNmprecioVenta() {
		return this.nmprecioVenta;
	}

	public void setNmprecioVenta(Integer nmprecioVenta) {
		this.nmprecioVenta = nmprecioVenta;
	}

	public Integer getNmprecioCompra() {
		return this.nmprecioCompra;
	}

	public void setNmprecioCompra(Integer nmprecioCompra) {
		this.nmprecioCompra = nmprecioCompra;
	}

	public Integer getNmsaldo() {
		return this.nmsaldo;
	}

	public void setNmsaldo(Integer nmsaldo) {
		this.nmsaldo = nmsaldo;
	}

	public String getDsimagenProducto() {
		return this.dsimagenProducto;
	}

	public void setDsimagenProducto(String dsimagenProducto) {
		this.dsimagenProducto = dsimagenProducto;
	}

	public String getDsimagenFichatec() {
		return this.dsimagenFichatec;
	}

	public void setDsimagenFichatec(String dsimagenFichatec) {
		this.dsimagenFichatec = dsimagenFichatec;
	}

	public Integer getNmimpuesto() {
		return this.nmimpuesto;
	}

	public void setNmimpuesto(Integer nmimpuesto) {
		this.nmimpuesto = nmimpuesto;
	}

	public Integer getMncantidadMin() {
		return this.mncantidadMin;
	}

	public void setMncantidadMin(Integer mncantidadMin) {
		this.mncantidadMin = mncantidadMin;
	}

	public String getMncantidadMax() {
		return this.mncantidadMax;
	}

	public void setMncantidadMax(String mncantidadMax) {
		this.mncantidadMax = mncantidadMax;
	}
}
