package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdCategoria generated by hbm2java
 */
public class ProdCategoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcategoria;
	private String dsnombre;
	private String dsdescripccion;
	private String dstipoDatoCategoria;
//	private Set prodProductoCategorias = new HashSet(0);

	public ProdCategoria() {
	}

	public ProdCategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	public ProdCategoria(int idcategoria, String dsnombre, String dsdescripccion, String dstipoDatoCategoria) {
		this.idcategoria = idcategoria;
		this.dsnombre = dsnombre;
		this.dsdescripccion = dsdescripccion;
		this.dstipoDatoCategoria = dstipoDatoCategoria;
	}

	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripccion() {
		return this.dsdescripccion;
	}

	public void setDsdescripccion(String dsdescripccion) {
		this.dsdescripccion = dsdescripccion;
	}

	public String getDstipoDatoCategoria() {
		return this.dstipoDatoCategoria;
	}

	public void setDstipoDatoCategoria(String dstipoDatoCategoria) {
		this.dstipoDatoCategoria = dstipoDatoCategoria;
	}
}
