package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * ProdProductoTipo generated by hbm2java
 */
public class ProdProductoTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idproductoTipo;
	private String dsnombre;
	private String dsdescripcion;
//	private Set prodProductos = new HashSet(0);

	public ProdProductoTipo() {
	}

	public ProdProductoTipo(String dsnombre, String dsdescripcion) {
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public Integer getIdproductoTipo() {
		return this.idproductoTipo;
	}

	public void setIdproductoTipo(Integer idproductoTipo) {
		this.idproductoTipo = idproductoTipo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
