package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * RrhhRolTipo generated by hbm2java
 */
public class RrhhRolTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrolTipo;
	private String dsnombre;
	private String dsdescripccion;
//	private Set rrhhUsuarioRoleses = new HashSet(0);

	public RrhhRolTipo() {
	}

	public RrhhRolTipo(int idrolTipo) {
		this.idrolTipo = idrolTipo;
	}

	public RrhhRolTipo(int idrolTipo, String dsnombre, String dsdescripccion) {
		this.idrolTipo = idrolTipo;
		this.dsnombre = dsnombre;
		this.dsdescripccion = dsdescripccion;
	}

	public int getIdrolTipo() {
		return this.idrolTipo;
	}

	public void setIdrolTipo(int idrolTipo) {
		this.idrolTipo = idrolTipo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripccion() {
		return this.dsdescripccion;
	}

	public void setDsdescripccion(String dsdescripccion) {
		this.dsdescripccion = dsdescripccion;
	}
}
