package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RrhhRolesAplicativo generated by hbm2java
 */
public class RrhhRolesAplicativo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrolAplicativo;
	private RrhhAplicativo rrhhAplicativo;
	private RrhhUsuarioRoles rrhhUsuarioRoles;
	private Date feactivacion;

	public RrhhRolesAplicativo() {
	}

	public RrhhRolesAplicativo(int idrolAplicativo) {
		this.idrolAplicativo = idrolAplicativo;
	}

	public RrhhRolesAplicativo(int idrolAplicativo, RrhhAplicativo rrhhAplicativo, RrhhUsuarioRoles rrhhUsuarioRoles,
			Date feactivacion) {
		this.idrolAplicativo = idrolAplicativo;
		this.rrhhAplicativo = rrhhAplicativo;
		this.rrhhUsuarioRoles = rrhhUsuarioRoles;
		this.feactivacion = feactivacion;
	}

	public int getIdrolAplicativo() {
		return this.idrolAplicativo;
	}

	public void setIdrolAplicativo(int idrolAplicativo) {
		this.idrolAplicativo = idrolAplicativo;
	}

	public RrhhAplicativo getRrhhAplicativo() {
		return this.rrhhAplicativo;
	}

	public void setRrhhAplicativo(RrhhAplicativo rrhhAplicativo) {
		this.rrhhAplicativo = rrhhAplicativo;
	}

	public RrhhUsuarioRoles getRrhhUsuarioRoles() {
		return this.rrhhUsuarioRoles;
	}

	public void setRrhhUsuarioRoles(RrhhUsuarioRoles rrhhUsuarioRoles) {
		this.rrhhUsuarioRoles = rrhhUsuarioRoles;
	}

	public Date getFeactivacion() {
		return this.feactivacion;
	}

	public void setFeactivacion(Date feactivacion) {
		this.feactivacion = feactivacion;
	}

}
