package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * RrhhAplicativo generated by hbm2java
 */
public class RrhhAplicativo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idaplicativo;
	private String dsnombre;
	private String dsdireccion;
	private String dsdetalles;
//	private Set rrhhRolesAplicativos = new HashSet(0);

	public RrhhAplicativo() {
	}

	public RrhhAplicativo(int idaplicativo) {
		this.idaplicativo = idaplicativo;
	}

	public RrhhAplicativo(int idaplicativo, String dsnombre, String dsdireccion, String dsdetalles) {
		this.idaplicativo = idaplicativo;
		this.dsnombre = dsnombre;
		this.dsdireccion = dsdireccion;
		this.dsdetalles = dsdetalles;
	}

	public int getIdaplicativo() {
		return this.idaplicativo;
	}

	public void setIdaplicativo(int idaplicativo) {
		this.idaplicativo = idaplicativo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdireccion() {
		return this.dsdireccion;
	}

	public void setDsdireccion(String dsdireccion) {
		this.dsdireccion = dsdireccion;
	}

	public String getDsdetalles() {
		return this.dsdetalles;
	}

	public void setDsdetalles(String dsdetalles) {
		this.dsdetalles = dsdetalles;
	}
}
