package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RrhhUsuario generated by hbm2java
 */
public class RrhhUsuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idusuario;
	private TercPersona tercPersona;
	private String dsalias;
	private String dspregunta;
	private String dsrespuesta;
	private Date fecreacion;
	private String dsbloqueo;
	private Date febloqueo;
	private String dspassword;
	private Date feactualizacion;
//	private Set rrhhUsuarioRoleses = new HashSet(0);

	public RrhhUsuario() {
	}

	public RrhhUsuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public RrhhUsuario(int idusuario, TercPersona tercPersona, String dsalias, String dspregunta, String dsrespuesta,
			Date fecreacion, String dsbloqueo, Date febloqueo, String dspassword, Date feactualizacion) {
		super();
		this.idusuario = idusuario;
		this.tercPersona = tercPersona;
		this.dsalias = dsalias;
		this.dspregunta = dspregunta;
		this.dsrespuesta = dsrespuesta;
		this.fecreacion = fecreacion;
		this.dsbloqueo = dsbloqueo;
		this.febloqueo = febloqueo;
		this.dspassword = dspassword;
		this.feactualizacion = feactualizacion;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public TercPersona getTercPersona() {
		return tercPersona;
	}

	public void setTercPersona(TercPersona tercPersona) {
		this.tercPersona = tercPersona;
	}

	public String getDsalias() {
		return this.dsalias;
	}

	public void setDsalias(String dsalias) {
		this.dsalias = dsalias;
	}

	public String getDspregunta() {
		return this.dspregunta;
	}

	public void setDspregunta(String dspregunta) {
		this.dspregunta = dspregunta;
	}

	public String getDsrespuesta() {
		return this.dsrespuesta;
	}

	public void setDsrespuesta(String dsrespuesta) {
		this.dsrespuesta = dsrespuesta;
	}

	public Date getFecreacion() {
		return this.fecreacion;
	}

	public void setFecreacion(Date fecreacion) {
		this.fecreacion = fecreacion;
	}

	public String getDsbloqueo() {
		return this.dsbloqueo;
	}

	public void setDsbloqueo(String dsbloqueo) {
		this.dsbloqueo = dsbloqueo;
	}

	public Date getFebloqueo() {
		return this.febloqueo;
	}

	public void setFebloqueo(Date febloqueo) {
		this.febloqueo = febloqueo;
	}

	public String getDspassword() {
		return this.dspassword;
	}

	public void setDspassword(String dspassword) {
		this.dspassword = dspassword;
	}

	public Date getFeactualizacion() {
		return this.feactualizacion;
	}

	public void setFeactualizacion(Date feactualizacion) {
		this.feactualizacion = feactualizacion;
	}
}
