package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * RrhhRoles generated by hbm2java
 */
public class RrhhRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrol;
	private String dsnombre;
	private String dsdescripcion;
//	private Set rrhhUsuarioRoleses = new HashSet(0);

	public RrhhRoles() {
	}

	public RrhhRoles(int idrol) {
		this.idrol = idrol;
	}

	public RrhhRoles(int idrol, String dsnombre, String dsdescripcion) {
		this.idrol = idrol;
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
