package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * RrhhRolesOrganizaciones generated by hbm2java
 */
public class RrhhRolesOrganizaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrolOrganizacion;
	private ContOrganizacionInterna contOrganizacionInterna;
	private RrhhUsuarioRoles rrhhUsuarioRoles;

	public RrhhRolesOrganizaciones() {
	}

	public RrhhRolesOrganizaciones(int idrolOrganizacion) {
		this.idrolOrganizacion = idrolOrganizacion;
	}

	public RrhhRolesOrganizaciones(int idrolOrganizacion, ContOrganizacionInterna contOrganizacionInterna,
			RrhhUsuarioRoles rrhhUsuarioRoles) {
		this.idrolOrganizacion = idrolOrganizacion;
		this.contOrganizacionInterna = contOrganizacionInterna;
		this.rrhhUsuarioRoles = rrhhUsuarioRoles;
	}

	public int getIdrolOrganizacion() {
		return this.idrolOrganizacion;
	}

	public void setIdrolOrganizacion(int idrolOrganizacion) {
		this.idrolOrganizacion = idrolOrganizacion;
	}

	public ContOrganizacionInterna getContOrganizacionInterna() {
		return this.contOrganizacionInterna;
	}

	public void setContOrganizacionInterna(ContOrganizacionInterna contOrganizacionInterna) {
		this.contOrganizacionInterna = contOrganizacionInterna;
	}

	public RrhhUsuarioRoles getRrhhUsuarioRoles() {
		return this.rrhhUsuarioRoles;
	}

	public void setRrhhUsuarioRoles(RrhhUsuarioRoles rrhhUsuarioRoles) {
		this.rrhhUsuarioRoles = rrhhUsuarioRoles;
	}

}
