package co.weepa.smile.contabilidad.dto;
// default package
// Generated 31-oct-2015 11:05:46 by Hibernate Tools 4.3.1.Final

/**
 * TercClasificacionTipo generated by hbm2java
 */
public class TercClasificacionTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idclasificacionTipo;
	private String dsnombre;
	private String dsdescripcion;
//	private Set tercTerceroClasificacions = new HashSet(0);

	public TercClasificacionTipo() {
	}

	public TercClasificacionTipo(int idclasificacionTipo) {
		this.idclasificacionTipo = idclasificacionTipo;
	}

	public TercClasificacionTipo(int idclasificacionTipo, String dsnombre, String dsdescripcion) {
		this.idclasificacionTipo = idclasificacionTipo;
		this.dsnombre = dsnombre;
		this.dsdescripcion = dsdescripcion;
	}

	public int getIdclasificacionTipo() {
		return this.idclasificacionTipo;
	}

	public void setIdclasificacionTipo(int idclasificacionTipo) {
		this.idclasificacionTipo = idclasificacionTipo;
	}

	public String getDsnombre() {
		return this.dsnombre;
	}

	public void setDsnombre(String dsnombre) {
		this.dsnombre = dsnombre;
	}

	public String getDsdescripcion() {
		return this.dsdescripcion;
	}

	public void setDsdescripcion(String dsdescripcion) {
		this.dsdescripcion = dsdescripcion;
	}
}
